name: compilacion-manual

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  # URL de GitHub Container Registry
  GHCR_IO: ghcr.io/${{ github.repository }}:latest
  # Token de GitHub Package Registry
  TOKEN_PKG: ${{ secrets.TOKEN_PKG_API_GHA }}
  # Nombre de usuario del propietario del repositorio
  ACTOR: ${{ github.repository_owner }}
  #
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out the repository
        uses: actions/checkout@main

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.TOKEN_PKG_API_GHA }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ github.repository }}:latest
          labels: ${{ steps.meta.outputs.labels }}
          # cache-from: type=gha
