name: Compilación manual

on:
  workflow_dispatch: # Allow manual runs
  push:
    branches:
      - main # Trigger on pushes to main branch (optional: add `|| true` for error handling)

env:
  TOKEN_PKG: ${{ secrets.TOKEN_PKG_API_GHA }} # Reference GitHub Secret
  GHCR_IO: ghcr.io/${{ github.repository }}:latest
  ACTOR: ${{ github.repository_owner }}

jobs:
  configure-docker: # Optional: Remove this job if using Docker Credential Helper
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

  build:
    runs-on: ubuntu-latest
    needs: configure-docker # Only run after configure-docker (optional)
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Iniciar sesión en GitHub Container Registry con Docker
        # Leverage pre-configured credential helper (if used)
        run: docker login ghcr.io -u $ACTOR --password-stdin

      - name: Construyendo imagen
        run: |
          docker build -t $GHCR_IO .

      - name: Publicando imagen
        run: |
          docker push $GHCR_IO
