name: Compilaci贸n manual

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  TOKEN_PKG: ${{ secrets.TOKEN_PKG_API_GHA }}
  GHCR_IO: ghcr.io/${{ github.repository }}:latest
  ACTOR: ${{ github.repository_owner }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configurar credenciales de Docker
        run: |
          # Define el nombre de usuario y token de GitHub Container Registry
          GHCR_USERNAME=$ACTOR
          GHCR_TOKEN=$TOKEN_PKG

          # Crea un directorio para el archivo de configuraci贸n de Docker
          mkdir -p ~/.docker

          # Crea un archivo de configuraci贸n para Docker
          cat <<EOF > ~/.docker/config.json
          {
            "credHelpers": {
              "ghcr.io": "ghcr"
            }
          }
          EOF

          # Crea un helper de credenciales personalizado para GHCR
          cat <<EOF > ~/.docker/config.sh
          #!/bin/bash
          echo "{\"Username\":\"$GHCR_USERNAME\",\"Secret\":\"$GHCR_TOKEN\"}"
          EOF

          # Cambia los permisos para que el helper de credenciales sea ejecutable
          chmod +x ~/.docker/config.sh

      - name: Iniciar sesi贸n en GitHub Container Registry con Docker
        run: |
          docker login ghcr.io -u $ACTOR --password-stdin <<< "$(cat ~/.docker/config.sh)"

      - name: Construyendo imagen
        run: |
          docker build -t $GHCR_IO .

      - name: Publicando imagen
        run: |
          docker push $GHCR_IO
