name: compilacion-manual

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  # URL de GitHub Container Registry
  GHCR_IO: ghcr.io/${{ github.repository }}:latest
  # Token de GitHub Package Registry
  TOKEN_PKG: ${{ secrets.TOKEN_PKG_API_GHA }}
  # Nombre de usuario del propietario del repositorio
  ACTOR: ${{ github.repository_owner }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: $ACTOR
          password: $TOKEN_PKG

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: $GHCR_IO
