name: Compilación manual

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  TOKEN_PKG: ${{ secrets.TOKEN_PKG_API_GHA }}
  GHCR_IO: ghcr.io/${{ github.repository }}:latest
  ACTOR: ${{ github.repository_owner }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configurar credenciales de Docker
        run: |
          echo "{\"auths\":{\"ghcr.io\":{\"username\":\"$ACTOR\",\"password\":\"$TOKEN_PKG\"}}}" > ~/.docker/config.json

      - name: Iniciar sesión en GitHub Container Registry con Docker
        run: |
          docker login ghcr.io -u $ACTOR --password-stdin < ~/.docker/config.json

      - name: Construyendo imagen
        run: |
          docker build -t $GHCR_IO .

      - name: Publicando imagen
        run: |
          docker push $GHCR_IO
